### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by NateDogg1232** [TheCool1Kevin/LiquiDOS#4]
Configure doesn't check for nasm

**Comment by TheCool1Kevin** [comment]
Are you sure?

https://github.com/TheCool1Kevin/LiquiDOS/blob/master/configure.ac#L27

**Comment by NateDogg1232** [comment]
Huh.

But you don't check for non Debian based distros, because I use Arch and they use pacman.

**Comment by TheCool1Kevin** [comment]
Ah, I see. I'll add this feature when I have time to. Thanks.

**Comment by TheCool1Kevin** [comment]
This issue has been fixed in https://github.com/TheCool1Kevin/LiquiDOS/commit/e1b78b51b42a5ce04fa0dd43de8446efee27b896
with the addition of `install-prereq.sh`, as installing within `configure` is not viable.
